#!/usr/bin/env python3
"""
Integration Agent - Self-Adaptation Feature Installation
=========================================================

The Integration Agent fulfills desires generated by the Curiosity Engine.
It handles the actual work of:

1. Requesting feature content from source nodes
2. Translating paths and configs for local environment
3. Installing/adapting features to local setup
4. Verifying successful integration
5. Reporting fulfillment status

This agent does NOT simply copy files. It UNDERSTANDS and ADAPTS features
to work in the local node's unique environment (paths, venvs, services).

Communication happens via:
- Enhanced Memory MCP (cluster shared memories)
- Node Chat (direct peer requests)
- File system for local installation
"""

import json
import sqlite3
import platform
import re
import shutil
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional, Tuple
import logging
import requests

# Import sibling modules
from node_identity_service import NodeIdentityService, _get_storage_base
from curiosity_engine import CuriosityEngine, Desire

STORAGE_BASE = _get_storage_base()
CLAUDE_HOME = Path.home() / ".claude"
DB_PATH = Path(STORAGE_BASE) / "databases" / "cluster" / "node_registry.db"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("integration-agent")


class IntegrationAgent:
    """
    Fulfills feature desires by adapting and installing features from peers.

    Key principle: Each node adapts features to its OWN environment.
    No blind copying - everything is translated and verified.
    """

    def __init__(self):
        self.identity_service = NodeIdentityService()
        self.curiosity_engine = CuriosityEngine()
        self.node_id = self.identity_service.node_id

        # Ensure identity is current
        self.identity_service.generate_identity()
        self.identity = self.identity_service.identity

        # Path translation rules
        self.path_rules = self.identity.get("adaptation_map", {}).get("path_rules", {})

        logger.info(f"Integration Agent initialized for {self.node_id}")

    def process_fulfillment_queue(self) -> Dict[str, Any]:
        """
        Process all desires in the fulfillment queue.

        Returns summary of fulfillment attempts.
        """
        queue = self.curiosity_engine.get_fulfillment_queue()

        result = {
            "processed_at": datetime.now().isoformat(),
            "node_id": self.node_id,
            "total_in_queue": len(queue),
            "attempted": 0,
            "successful": 0,
            "failed": 0,
            "results": []
        }

        for item in queue:
            desire_data = item["desire"]
            adaptation_plan = item["adaptation_plan"]

            logger.info(f"Processing desire: {desire_data['feature_type']}:{desire_data['feature_name']}")

            # Mark as integrating
            self.curiosity_engine.update_desire_status(
                desire_data["id"], "integrating",
                f"Starting integration attempt"
            )

            # Attempt fulfillment
            try:
                success, details = self._fulfill_desire(desire_data, adaptation_plan)

                if success:
                    self.curiosity_engine.update_desire_status(
                        desire_data["id"], "fulfilled", details
                    )
                    result["successful"] += 1
                else:
                    self.curiosity_engine.update_desire_status(
                        desire_data["id"], "failed", details
                    )
                    result["failed"] += 1

                result["results"].append({
                    "desire_id": desire_data["id"],
                    "feature": f"{desire_data['feature_type']}:{desire_data['feature_name']}",
                    "success": success,
                    "details": details
                })

            except Exception as e:
                logger.error(f"Error fulfilling desire {desire_data['id']}: {e}")
                self.curiosity_engine.update_desire_status(
                    desire_data["id"], "failed", str(e)
                )
                result["failed"] += 1
                result["results"].append({
                    "desire_id": desire_data["id"],
                    "feature": f"{desire_data['feature_type']}:{desire_data['feature_name']}",
                    "success": False,
                    "details": str(e)
                })

            result["attempted"] += 1

        return result

    def _fulfill_desire(self, desire: Dict, plan: Dict) -> Tuple[bool, str]:
        """
        Fulfill a single desire using its adaptation plan.

        Returns (success, details_message)
        """
        feature_type = desire["feature_type"]
        feature_name = desire["feature_name"]
        source_node = desire["source_node"]

        # Route to appropriate handler
        if feature_type == "skill":
            return self._integrate_skill(feature_name, source_node, plan)
        elif feature_type == "agent":
            return self._integrate_agent(feature_name, source_node, plan)
        elif feature_type == "command":
            return self._integrate_command(feature_name, source_node, plan)
        elif feature_type == "hook_helper":
            return self._integrate_hook_helper(feature_name, source_node, plan)
        elif feature_type == "mcp_server":
            return self._integrate_mcp_server(feature_name, source_node, plan)
        else:
            return False, f"Unknown feature type: {feature_type}"

    def _request_feature_content(self, feature_type: str, feature_name: str,
                                  source_node: str) -> Optional[str]:
        """
        Request feature content from source node.

        Uses cluster shared memory to find the feature definition.
        """
        # Try to get from cluster shared memory first
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        # Check if source node has shared their configuration
        cursor.execute("""
            SELECT full_identity_json FROM node_identities
            WHERE node_id = ?
        """, (source_node,))

        row = cursor.fetchone()
        conn.close()

        if not row:
            logger.warning(f"No identity found for source node {source_node}")
            return None

        source_identity = json.loads(row[0])

        # Determine the file path based on feature type
        source_env = source_identity.get("environment", {})
        source_claude_home = source_env.get("claude_home", "~/.claude")

        # Map feature type to directory
        type_to_dir = {
            "skill": "skills",
            "agent": "agents",
            "command": "commands",
            "hook_helper": "hooks"
        }

        if feature_type not in type_to_dir:
            return None

        # For now, we create a feature request that will be fulfilled
        # via the node-chat system or manual sync
        request = {
            "type": "feature_request",
            "feature_type": feature_type,
            "feature_name": feature_name,
            "source_node": source_node,
            "requesting_node": self.node_id,
            "source_path": f"{source_claude_home}/{type_to_dir[feature_type]}/{feature_name}.md",
            "requested_at": datetime.now().isoformat()
        }

        # Store request in shared memory
        self._store_feature_request(request)

        # For now, try to read directly if we have filesystem access
        # (this works for nodes with shared storage or SMB mounts)
        return self._try_direct_read(source_node, feature_type, feature_name)

    def _try_direct_read(self, source_node: str, feature_type: str,
                         feature_name: str) -> Optional[str]:
        """
        Try to read feature content directly if accessible.

        This works when:
        - Nodes share storage (SMB mount)
        - Files have been synced to a shared location
        - Running on orchestrator with access to all node configs
        """
        # Check cluster shared feature store
        shared_features = Path(STORAGE_BASE) / "cluster-deployment" / "shared_features"
        shared_file = shared_features / source_node / feature_type / f"{feature_name}.md"

        if shared_file.exists():
            logger.info(f"Found shared feature: {shared_file}")
            return shared_file.read_text()

        # Check if feature was exported by source node
        export_file = Path(STORAGE_BASE) / "cluster-deployment" / f"export_{source_node}" / \
                     feature_type / f"{feature_name}.md"

        if export_file.exists():
            logger.info(f"Found exported feature: {export_file}")
            return export_file.read_text()

        logger.warning(f"Feature not directly accessible: {feature_type}/{feature_name} from {source_node}")
        return None

    def _store_feature_request(self, request: Dict):
        """Store feature request for async fulfillment"""
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS feature_requests (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                requesting_node TEXT NOT NULL,
                source_node TEXT NOT NULL,
                feature_type TEXT NOT NULL,
                feature_name TEXT NOT NULL,
                source_path TEXT,
                status TEXT DEFAULT 'pending',
                content TEXT,
                requested_at TEXT NOT NULL,
                fulfilled_at TEXT
            )
        """)

        cursor.execute("""
            INSERT INTO feature_requests
            (requesting_node, source_node, feature_type, feature_name,
             source_path, requested_at)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            request["requesting_node"],
            request["source_node"],
            request["feature_type"],
            request["feature_name"],
            request.get("source_path"),
            request["requested_at"]
        ))

        conn.commit()
        conn.close()

    def _translate_content(self, content: str, plan: Dict) -> str:
        """
        Translate paths and configs in content for local environment.

        This is the KEY adaptation step - making foreign content work locally.
        """
        translated = content

        # Apply path translations
        path_rules = plan.get("path_translations", self.path_rules)
        for source_path, local_path in path_rules.items():
            translated = translated.replace(source_path, local_path)

        # Handle ~ expansion in content
        translated = translated.replace("~/", str(Path.home()) + "/")

        # Platform-specific adjustments
        if platform.system() == "Linux":
            # Convert macOS-specific paths
            translated = translated.replace("/Volumes/SSDRAID0/agentic-system", STORAGE_BASE)
            translated = translated.replace("/Users/marc", str(Path.home()))
        elif platform.system() == "Darwin":
            # Convert Linux-specific paths
            translated = translated.replace("/home/marc/agentic-system", STORAGE_BASE)
            translated = translated.replace("/mnt/agentic-system", STORAGE_BASE)

        return translated

    def _integrate_skill(self, name: str, source_node: str, plan: Dict) -> Tuple[bool, str]:
        """Integrate a skill from source node"""
        content = self._request_feature_content("skill", name, source_node)

        if not content:
            return False, f"Could not retrieve skill content from {source_node}"

        # Translate content
        translated = self._translate_content(content, plan)

        # Install skill
        skills_dir = CLAUDE_HOME / "skills"
        skills_dir.mkdir(parents=True, exist_ok=True)

        skill_file = skills_dir / f"{name}.md"

        # Backup if exists
        if skill_file.exists():
            backup = skill_file.with_suffix(".md.bak")
            shutil.copy2(skill_file, backup)

        # Write translated skill
        skill_file.write_text(translated)

        logger.info(f"Installed skill: {name}")
        return True, f"Skill '{name}' installed from {source_node}"

    def _integrate_agent(self, name: str, source_node: str, plan: Dict) -> Tuple[bool, str]:
        """Integrate an agent definition from source node"""
        content = self._request_feature_content("agent", name, source_node)

        if not content:
            return False, f"Could not retrieve agent content from {source_node}"

        # Translate content
        translated = self._translate_content(content, plan)

        # Install agent
        agents_dir = CLAUDE_HOME / "agents"
        agents_dir.mkdir(parents=True, exist_ok=True)

        agent_file = agents_dir / f"{name}.md"

        if agent_file.exists():
            backup = agent_file.with_suffix(".md.bak")
            shutil.copy2(agent_file, backup)

        agent_file.write_text(translated)

        logger.info(f"Installed agent: {name}")
        return True, f"Agent '{name}' installed from {source_node}"

    def _integrate_command(self, name: str, source_node: str, plan: Dict) -> Tuple[bool, str]:
        """Integrate a slash command from source node"""
        content = self._request_feature_content("command", name, source_node)

        if not content:
            return False, f"Could not retrieve command content from {source_node}"

        # Translate content
        translated = self._translate_content(content, plan)

        # Install command
        commands_dir = CLAUDE_HOME / "commands"
        commands_dir.mkdir(parents=True, exist_ok=True)

        command_file = commands_dir / f"{name}.md"

        if command_file.exists():
            backup = command_file.with_suffix(".md.bak")
            shutil.copy2(command_file, backup)

        command_file.write_text(translated)

        logger.info(f"Installed command: {name}")
        return True, f"Command '/{name}' installed from {source_node}"

    def _integrate_hook_helper(self, name: str, source_node: str, plan: Dict) -> Tuple[bool, str]:
        """Integrate a hook helper module from source node"""
        content = self._request_feature_content("hook_helper", name, source_node)

        if not content:
            return False, f"Could not retrieve hook module content from {source_node}"

        # Translate content
        translated = self._translate_content(content, plan)

        # Check for Python import issues
        try:
            compile(translated, name, 'exec')
        except SyntaxError as e:
            return False, f"Syntax error in hook module: {e}"

        # Install hook
        hooks_dir = CLAUDE_HOME / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)

        hook_file = hooks_dir / name

        if hook_file.exists():
            backup = hook_file.with_suffix(".py.bak")
            shutil.copy2(hook_file, backup)

        hook_file.write_text(translated)

        logger.info(f"Installed hook helper: {name}")
        return True, f"Hook module '{name}' installed from {source_node}"

    def _integrate_mcp_server(self, name: str, source_node: str, plan: Dict) -> Tuple[bool, str]:
        """
        Integrate an MCP server configuration from source node.

        This is more complex as it requires:
        1. Getting the server config
        2. Checking if server code exists locally
        3. Translating paths in config
        4. Adding to ~/.claude.json
        """
        # Get source node's MCP config
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT full_identity_json FROM node_identities
            WHERE node_id = ?
        """, (source_node,))

        row = cursor.fetchone()
        conn.close()

        if not row:
            return False, f"No identity found for {source_node}"

        source_identity = json.loads(row[0])
        source_mcp = source_identity.get("claude_config", {}).get("mcp_servers", {})

        # Find the server config
        server_config = None
        for level in ["user_level", "project_level"]:
            if name in source_mcp.get(level, {}):
                server_config = source_mcp[level][name]
                break

        if not server_config:
            return False, f"MCP server '{name}' not found in {source_node}'s config"

        # Translate the command path
        cmd = server_config.get("command", "")
        translated_cmd = self._translate_content(cmd, plan)

        # Check if the server exists locally
        # Try to find the server in common locations
        server_locations = [
            Path(STORAGE_BASE) / "mcp-servers" / name,
            Path(STORAGE_BASE) / "mcp-servers" / f"{name}-mcp",
        ]

        server_found = False
        for loc in server_locations:
            if loc.exists():
                server_found = True
                break

        if not server_found:
            return False, f"MCP server '{name}' code not found locally. Manual installation required."

        # Add to local MCP config
        config_file = Path.home() / ".claude.json"

        if config_file.exists():
            with open(config_file) as f:
                claude_config = json.load(f)
        else:
            claude_config = {"mcpServers": {}}

        if "mcpServers" not in claude_config:
            claude_config["mcpServers"] = {}

        # Add translated config
        claude_config["mcpServers"][name] = {
            "command": translated_cmd,
            "disabled": False
        }

        # Backup and write
        if config_file.exists():
            backup = config_file.with_suffix(".json.bak")
            shutil.copy2(config_file, backup)

        with open(config_file, 'w') as f:
            json.dump(claude_config, f, indent=2)

        logger.info(f"Added MCP server config: {name}")
        return True, f"MCP server '{name}' config added from {source_node}. Restart Claude Code to load."

    def export_local_features(self) -> Dict[str, Any]:
        """
        Export this node's features for other nodes to discover.

        This creates a shareable feature catalog that other nodes
        can use to fulfill their desires.
        """
        export_dir = Path(STORAGE_BASE) / "cluster-deployment" / f"export_{self.node_id}"
        export_dir.mkdir(parents=True, exist_ok=True)

        exported = {
            "node_id": self.node_id,
            "exported_at": datetime.now().isoformat(),
            "features": {
                "skills": [],
                "agents": [],
                "commands": [],
                "hook_helpers": []
            }
        }

        # Export skills
        skills_dir = CLAUDE_HOME / "skills"
        if skills_dir.exists():
            dest_dir = export_dir / "skill"
            dest_dir.mkdir(exist_ok=True)
            for skill in skills_dir.glob("*.md"):
                shutil.copy2(skill, dest_dir / skill.name)
                exported["features"]["skills"].append(skill.stem)

        # Export agents
        agents_dir = CLAUDE_HOME / "agents"
        if agents_dir.exists():
            dest_dir = export_dir / "agent"
            dest_dir.mkdir(exist_ok=True)
            for agent in agents_dir.glob("*.md"):
                shutil.copy2(agent, dest_dir / agent.name)
                exported["features"]["agents"].append(agent.stem)

        # Export commands
        commands_dir = CLAUDE_HOME / "commands"
        if commands_dir.exists():
            dest_dir = export_dir / "command"
            dest_dir.mkdir(exist_ok=True)
            for cmd in commands_dir.glob("*.md"):
                shutil.copy2(cmd, dest_dir / cmd.name)
                exported["features"]["commands"].append(cmd.stem)

        # Export hook helpers (Python scripts, shell scripts, and other executables)
        hooks_dir = CLAUDE_HOME / "hooks"
        if hooks_dir.exists():
            dest_dir = export_dir / "hook_helper"
            dest_dir.mkdir(exist_ok=True)
            # Export all hook scripts (.py, .sh, .md)
            for pattern in ["*.py", "*.sh", "*.md"]:
                for hook in hooks_dir.glob(pattern):
                    # Skip if file doesn't exist (broken symlink, etc.)
                    if not hook.exists():
                        continue
                    # Skip main hook files, only export helpers
                    if hook.name not in ["pre-tool-use.py", "post-tool-use.py",
                                         "session-start.py", "session-end.py"]:
                        try:
                            shutil.copy2(hook, dest_dir / hook.name)
                            exported["features"]["hook_helpers"].append(hook.name)
                        except (OSError, IOError) as e:
                            logger.warning(f"Error copying hook file {hook}: {e}")

        # Save export manifest
        manifest_file = export_dir / "manifest.json"
        with open(manifest_file, 'w') as f:
            json.dump(exported, f, indent=2)

        logger.info(f"Exported features to {export_dir}")
        return exported


def main():
    """Run integration agent"""
    agent = IntegrationAgent()

    print("\n" + "="*80)
    print(f"INTEGRATION AGENT - {agent.node_id}")
    print("="*80)

    # First, export local features for other nodes
    print("\nExporting local features...")
    exported = agent.export_local_features()

    print(f"Exported:")
    print(f"  Skills: {len(exported['features']['skills'])}")
    print(f"  Agents: {len(exported['features']['agents'])}")
    print(f"  Commands: {len(exported['features']['commands'])}")
    print(f"  Hook Helpers: {len(exported['features']['hook_helpers'])}")

    # Process fulfillment queue
    print("\nProcessing fulfillment queue...")
    result = agent.process_fulfillment_queue()

    print(f"\nFulfillment Results:")
    print(f"  Total in queue: {result['total_in_queue']}")
    print(f"  Attempted: {result['attempted']}")
    print(f"  Successful: {result['successful']}")
    print(f"  Failed: {result['failed']}")

    if result['results']:
        print("\nDetails:")
        for r in result['results']:
            status = "OK" if r['success'] else "FAILED"
            print(f"  [{status}] {r['feature']}: {r['details']}")

    print("\n" + "="*80)


if __name__ == "__main__":
    main()
